#import "~/gql/fragments/MediaImage.gql"
#import "~/gql/fragments/GutenbergBlocks"

query Detail($uri: String!) {
    nodeByUri(uri: $uri) {
        ... on Page {
            id
            title
            to: uri
            ...GutenbergBlocks
            parent {
                node {
                    ... on Page {
                        id
                        title
                    }
                }
            }
            secondaryFeaturedImage {
                secondaryFeaturedImage {
                    ...MediaImage
                }
            }
            featuredImage {
                node {
                    ...MediaImage
                }
            }
            workMeta {
                type
                publication
                link
                talentName
                videoUrl
            }
        }
    }
}
