#import "~/gql/fragments/MediaImage.gql"

query Home {
    nodeByUri(uri: "/featured/") {
        ... on Page {
            id
            title
            children(first: 2) {
                nodes {
                    ... on Page {
                        id
                        title
                        children(first: 99) {
                            nodes {
                                ... on Page {
                                    id
                                    title
                                    secondaryFeaturedImage {
                                        secondaryFeaturedImage {
                                            ...MediaImage
                                        }
                                    }
                                    featuredImage {
                                        node {
                                            ...MediaImage
                                        }
                                    }
                                    workMeta {
                                        type
                                        publication
                                        link
                                        talentRelationship {
                                            ... on Page {
                                                title
                                                id
                                                uri
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
