#import "~/gql/fragments/MediaImage.gql"

query Roster($uri: String!) {
    nodeByUri(uri: $uri) {
        ... on Page {
            id
            title
            children(first: 99) {
                nodes {
                    ... on Page {
                        id
                        title
                        to: uri
                        featuredImage {
                            node {
                                ...MediaImage
                            }
                        }
                    }
                }
            }
        }
    }
}
